name: C/C++ CI/CD

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Environment
        run: |
          echo "Current directory: $(pwd): $GITHUB_WORKSPACE"
          ls 
          mkdir -m 755 ~/devel
          cd ~/devel
          mkdir -m 755 foo
          cd ~/devel/foo

          mkdir -m 755 src etc bin lib log man doc cert RPM
          echo "Current directory: $(pwd)"
          ls

          cd ~/devel/foo/src
          mkdir -m 755 facilities
          cd ~/devel/foo/src/facilities
          cp $GITHUB_WORKSPACE/includes/* ~/devel/foo/src/facilities
          cp $GITHUB_WORKSPACE/src/* ~/devel/foo/src/facilities
          cp $GITHUB_WORKSPACE/Makefile ~/devel/foo/src/facilities
          make
          echo "-- devel --"
          ls ~/devel/foo
          echo "-- foo --"
          ls ~/devel/foo/src
          echo "-- lib --"
          ls ~/devel/foo/lib
          
      - name: Setup Project
        run: |
          echo "Current directory: $(pwd): $GITHUB_WORKSPACE"
          cp ~/devel/foo/src/facilities/logging.h ~/devel/foo/include
          cp ~/devel/foo/src/facilities/config.h ~/devel/foo/include
          export INCLUDEDIR=~/foo/include
          make install
          cp $GITHUB_WORKSPACE/Makefile_01 ~/devel/foo/lib
          export LIBDIR=~/foo/lib
          make install
                    
          
      - name: Print
        run: |
           ls ~/devel/foo
           
      - name: Upload RPM
        uses: actions/upload-artifact@v2
        with:
          name: 15_puzzle
          path: rpm_pkg/rpmbuild/RPMS
