name: C/C++ CI/CD

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Environment
        run: |
          echo "Current directory: $(pwd): $GITHUB_WORKSPACE"
          ls 
          mkdir -m 755 ~/devel
          cd ~/devel
          mkdir -m 755 foo
          cd ~/devel/foo

          mkdir -m 755 src etc bin lib log man doc cert RPM
          echo "Current directory: $(pwd)"
          ls

          cd ~/devel/foo/src
          mkdir -m 755 facilities
          cd ~/devel/foo/src/facilities

          
          
      - name: Print
        run: |
           ls ~/devel/foo
           
      - name: Upload RPM
        uses: actions/upload-artifact@v2
        with:
          name: 15_puzzle
          path: rpm_pkg/rpmbuild/RPMS
